### PR TITLE
🐜[Bugfix] Fragment fingerprint crash 125

### LINKED ISSUE #125: 🦟[Bug Report] Crashlytics: FragmentFingerprint.java line 256
https://console.firebase.google.com/u/0/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/613beff8df52f6dd059a68fab63c01d9?time=1672474324000:1675066324000&sessionEventKey=63D77B810293000139B2FC22012803F9_1772800343544531809
**Describe the bug**

### PR DESCRIPTION
**Pull request by kcw-grunt**
# What was wrong?
When the user has a Fingerprint reader and has it enabled, the reader needs to dismiss the modal when the action has completed. The code had a smell in that it was removing an object that likely would still be alive.
This is found in FingerprintFragment.java line (265) now 237

[Firebase Crashlytics Link](https://console.firebase.google.com/u/0/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues?state=open&time=last-seven-days&tag=all&sort=eventCount)

# What was done
Rather than remove the activity which was a top 2 Crash in the app, the animation call `fingerPrintLayout.clearAnimation()`. This is suggested as a solution here:
 https://stackoverflow.com/questions/4750939/android-animation-is-not-finished-in-onanimationend
 
Will monitor this over the next few days.

Closes #125

### CODE REVIEW

**Comment by kcw-grunt** [comment]
Update: This is looking `good`

File: app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java [hunk 1]
```diff
@@ -248,12 +229,16 @@ private void animateSignalSlide(final boolean reverse) {
...
+                    .withLayer()
+                    .setInterpolator(new AnticipateInterpolator(2.0f))
+                    .setListener(new AnimatorListenerAdapter() {
                 @Override
                 public void onAnimationEnd(Animator animation) {
                     super.onAnimationEnd(animation);
-                    if (getActivity() != null)
-                        getActivity().getFragmentManager().beginTransaction().remove(FragmentFingerprint.this).commit();
+                    if (getActivity() != null) {
+                        fingerPrintLayout.clearAnimation();
```
Comment (kcw-grunt) [inline app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java:239]: This is the fix ...I believe the past implementation was removing a dead object

File: app/src/main/java/com/breadwallet/tools/util/BRConstants.java [hunk 2]
```diff
@@ -153,6 +153,7 @@ private BRConstants() {
     public static final String _20210804_TAULO = "ternio_API_user_log_out";
     public static final String _20210427_HCIEEH = "heartbeat_check_if_event_even_happens";
     public static final String _20220822_UTOU = "user_tapped_on_ud";
+    public static final String _20230131_NENR = "no_error_nominal_response";
```
Comment (kcw-grunt) [inline app/src/main/java/com/breadwallet/tools/util/BRConstants.java:156]: For analytics to make sure the process drops through the clearAnimation() call.

File: app/src/main/java/com/breadwallet/presenter/fragments/FragmentMenu.java [hunk 3]
```diff
@@ -53,7 +53,6 @@ public View onCreateView(LayoutInflater inflater,
         background.setOnClickListener(v -> {
             if (!BRAnimator.isClickAllowed()) return;
             closeMenu();
```
Comment (kcw-grunt) [inline app/src/main/java/com/breadwallet/presenter/fragments/FragmentMenu.java:55]: Whats the emoji for smh? @vsima

File: app/src/main/java/com/breadwallet/tools/security/AuthManager.java [hunk 4]
```diff
@@ -214,7 +214,7 @@ public void authPrompt(final Context context, String title, String message, bool
                 transaction.setCustomAnimations(0, 0, 0, R.animator.plain_300);
                 transaction.add(android.R.id.content, fingerprintFragment, FragmentFingerprint.class.getName());
                 transaction.addToBackStack(null);
-                if (!app.isDestroyed())
+                if (!app.isDestroyed() && !app.isFinishing())
```
Comment (kcw-grunt) [inline app/src/main/java/com/breadwallet/tools/security/AuthManager.java:217]: assuming this will block action when the object is still alive.

**Review by kcw-grunt — COMMENTED** [review]
LGTM.  Thanks alot @vsima

File: app/src/main/java/com/breadwallet/tools/security/AuthManager.java (hunk 4 above)
Comment (vsima) [reply app/src/main/java/com/breadwallet/tools/security/AuthManager.java:217]: exactly, since the next line was crashing the app in some cases, it's better to be extra careful. if the activity or fragment is starting to finish, we shouldn't attempt to navigate.
